version: '3.9'
services:
  configserver:
    image: registry.hub.docker.com/springland/tmx-confsvr
    ports:
      - "8888:8888"
  eurekasvr:
    image: registry.hub.docker.com/springland/tmx-eureka
    ports:
      - "8761:8761"

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - /home/fl/data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "eagle_eye_local"
  licensingservice:
    image: registry.hub.docker.com/springland/tmx-license
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
